### ISSUE TITLE
Add to a main client

### ISSUE THREAD

**Issue by cecilphillip** [dfrencham/ms-signalr-client#1]
Ever thought of making a pull request to the official SignalR repo to add JSPM support ?

**Comment by dfrencham** [comment]
hi mate. Sorry - only just noticed your comment. I'll look into it, JSPM support would be useful.

**Comment by ageroh** [comment]
Cna this package be used as standalone client (like the one used in C# signalr) without need of DOM and jquery ?  In order to use it as a server aplication for a hub in v,2.2
Thank you

**Comment by dfrencham** [comment]
@ageroh you could use it as a standalone client, sure - you don't need to run it within the context of a browser DOM. It does require jQuery, as it was written as a jQuery module.

This is the same SignalR library available in the NuGet package here: https://www.nuget.org/packages/Microsoft.AspNet.SignalR.JS/

I've simply split it out so it can be used with npm/jspm.

**Comment by dfrencham** [comment]
@cecilphillip I've looked into this, but there is a lot of hoops I would need to jump through for such a small contribution, and all we would end up with is a folder within the official repo with exactly the same as what we have here.

It should already work with jspm (with either npm or github as a source). I'll see if I can add it to the jspm registry to make life a bit easier.

**Comment by cecilphillip** [comment]
Not needed anymore. Closing
