### ISSUE TITLE
jQuery was not found. Please ensure jQuery

### ISSUE THREAD

**Issue by enginnerFrankLiu** [dfrencham/ms-signalr-client#15]
hi~thanks your attention for this issue;

I npm i ms-signalr-client

import $ from 'jquery';
import 'ms-signalr-client';

but meet some error:

![image](https://user-images.githubusercontent.com/41586100/43944531-c5e6005c-9cb1-11e8-8ab2-ff60de0eddf4.png)

backend: mvc5.2 ASP.NET SignalR 2.3.0 it work well
font-end:
npm webpack es6 react..... to do spa page
here is my font-end framework: https://ant.design/docs/react/introduce
here is same issue:https://github.com/SignalR/SignalR/issues/4162

please~ I run into this trouble for long days

**Comment by enginnerFrankLiu** [comment]
I find soluttion here:

import $ from 'jquery';
window.jQuery = $;
require('ms-signalr-client');

**Comment by ivanov84** [comment]
If someone has a problem like that then my solution:

I have ionic 4 that consists from webpack 3.12.0

Steps:
1. add in angular.json
`
"scripts": [
  "node_modules/jquery/dist/jquery.min.js",
  "node_modules/ms-signalr-client/jquery.signalR.min.js"
],
`
2. remove all ms-signalr declaration in yout ts
3. add this to yout ts:
`
declare var jQuery: any;
`
4. use signalR:
`
this.hubConnection = jQuery.hubConnection();
this.hubConnection.url = this.user.domainUrl + '/signalr';
this.hubConnection.qs = this.getQueryString();
this.hubProxy = this.hubConnection.createHubProxy('f'); 
`
