### ISSUE TITLE
Package jquery@3.0.0 is not working with ms-signalr-client

### ISSUE THREAD

**Issue by aliluyko89** [dfrencham/ms-signalr-client#4]
After packages re-installation package stopped working.
**Working** version:  jquery@2.2.4
**Not working** version:  jquery@3.0.0
**Error:** e.indexOf is not a function in jquery file.

**Comment by CoderDennis** [comment]
I'm not familiar with publishing updates to npm. Will you publish this as a new version so it's available there? Guessing that may also include bumping the package version, but I didn't know if I should have included that in my PR.

**Comment by dfrencham** [comment]
I just bumped the version number and published the update to npm. :)
