### ISSUE TITLE
Upgrade to 2.2.1 

### ISSUE THREAD

**Issue by patroza** [dfrencham/ms-signalr-client#6]
https://github.com/SignalR/SignalR/releases/tag/2.2.1

**Comment by dfrencham** [comment]
Replied in the referenced thread. 2.2.1 JS release is not available yet, only the pre-release version.

**Comment by alextkachuk** [comment]
@dfrencham  2.2.1 has been released!

https://github.com/SignalR/SignalR/pull/3748
https://github.com/SignalR/SignalR/releases

**Comment by dfrencham** [comment]
@alextkachuk @sickboy I've updated to the latest SignalR version and published the update to npm. Ref: 654e79ad18b530012bd23f621061696bd41fbefd

**Comment by alextkachuk** [comment]
@dfrencham Thanks!
