### ISSUE TITLE
Update breaks backwards-compatibility

### ISSUE THREAD

**Issue by tlumko** [dfrencham/ms-signalr-client#7]
My case: 
package.json -  "ms-signalr-client": "^2.2.0",
html - <script src="jquery.signalR-2.2.0.js"></script>

After yesterday update npm downloaded version 2.2.4, file name changes to "jquery.signalR-2.2.1.js".
You'd better remove version from file name.

**Comment by dfrencham** [comment]
Thanks for the heads up. I've removed the version number from the file names, bumped the package version, and published to npm. 

All sorted?

**Comment by tlumko** [comment]
Yes, thanks
