### ISSUE TITLE
jQuery v3 support

### ISSUE THREAD

**Issue by michelgb** [dfrencham/ms-signalr-client#9]
Hello, 

Have you considered supporting jQuery 3.x? I am using WebPack on my project and I just realized that jQuery is been duplicated because your dependencies are set to stop on version 2 ("jquery": "^2.2.0"). Is there any reason why jQuery 3.x is not supported?

Thanks,

**Comment by dfrencham** [comment]
The Microsoft repo references 1.6.4... so we are already past that.

https://github.com/SignalR/SignalR/tree/dev/src/Microsoft.AspNet.SignalR.Client.JS/Scripts

Have you tried signalR with jQuery 3.x ? if so, did it work?
